server:
  port: 8888
spring:
  security:
   oauth2:
    resourceserver:
    config:
     jwt:
     issuer-uri: "http://lpcalhost:9098/realms/micro-services"
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations